### ISSUE TITLE
Compile error using room-gallery with React

### ISSUE THREAD

**Issue by KJWXY** [formir/room-gallery#2]
Hi,
If possible, i would like to report the following issue i'm having while trying to use room-gallery in my React test app.

I've followed the instructions regarding installation\usage with React but i'm getting the following error:

![image](https://github.com/user-attachments/assets/9382dc5a-4856-4b9a-bed1-54ea20d9f9d2)

React is quite new for me, so maybe i'm missing something...but i also tried using room-gallery with a brand new (created from scratch) React app and the error is still there...

Could you please give me suggestion to solve this issue?

Many thanks!
Btw: room-gallery seems so cool! Great work!

**Comment by konrad-k** [comment]
Hello! Thank you for your submission, I am working on resolving the issue. The current version compiles only with support for an application written in React with TypeScript. I will soon release a version for JS.

**Comment by konrad-k** [comment]
Issue was fixes on version: https://github.com/formir/room-gallery/releases/tag/v1.4.0-dev

**Comment by KJWXY** [comment]
> Hello! Thank you for your submission, I am working on resolving the issue. The current version compiles only with support for an application written in React with TypeScript. I will soon release a version for JS.

Hi again, 

First of all thank you for your support, i've tried again (but had to manually copy latest release files, see below for the details) and i confirm you that is now working with a plain React app!

I would just like to report you that there seems to be a problem with the new release (v1.4.0-dev) not being installed with "npm install room-gallery". 

For some reason it will install the "v1.0.0-beta" version and even trying to use npm to manually target\install the latest version (npm install room-gallery@1.4.0-dev) will fail saying that version is not found.

Hope this can help
Thank you again!

**Comment by konrad-k** [comment]
Hello,
Sorry for the confusion, I need a bit more time to resolve this issue. I will get back to you within 24 hours. Best regards.

**Comment by konrad-k** [comment]
Hey, thank you for waiting, the issue has been fixed and tested in version 1.4.1-dev. However, please remember that if you want to use the production version, you will need to obtain the appropriate license :) Thank you and best regards! Konrad
